name: Deploy Development

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ecdsa
          chmod 600 ~/.ssh/id_ecdsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into server and deploy
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USERNAME@$SSH_HOST << 'EOF'
            cd $DEPLOY_PATH

            echo "🔄 Resetting and pulling latest code..."
            git reset --hard
            git pull origin main

            echo "📦 Installing dependencies..."
            composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "🧹 Clearing caches..."
            php artisan optimize:clear

            echo "⚙️ Caching config/routes/views..."
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "🛠 Running migrations..."
            php artisan migrate --force

            echo "✅ Deployment Complete!"
          EOF
